export type GeneratedTask = {
  title: string;
  description: string;
};

export function generateTask(prompt: string): GeneratedTask {
  return {
    title: `AI Task: ${prompt}`,
    description: 'Generated by TaskForge AI foundation service.'
  };
}
